// Copyright (c) 2026 John A Keeney, Entrouter. All rights reserved.
// Licensed under the Apache License, Version 2.0 with Additional Terms.
// NO COMMERCIAL USE without prior written authorization from Entrouter.
// Unauthorized commercial use will be prosecuted to the fullest extent of the law.
// See the LICENSE file in the project root for full license information.
// NOTICE: Removal of this header is a violation of the license.

//! Deterministic test vectors for all KK cryptographic primitives.
//!
//! Every value in this file was generated by `examples/generate_vectors.rs`
//! and is considered a canonical reference.  Any change to the underlying
//! primitives that causes a test here to fail is a **breaking change** and
//! must be explicitly acknowledged before updating the vectors.
//!
//! To regenerate vectors after an intentional change:
//!   `cargo run --example generate_vectors`
//! Then manually update the constants below and `KK_TEST_VECTORS.md`.

use kk_crypto::entropy::EntropySnapshot;
use kk_crypto::kk_mix::{
    kk_hash, kk_kdf, kk_mac, kk_mac_with_entropy, kk_permute, kk_permute_with_schedule,
    rotations_from_entropy, KkState,
};
use kk_crypto::session::RopeRatchet;
use kk_crypto::{decode, decode_aead, encode_aead_with_snapshot, encode_with_snapshot};

// ─── helpers ─────────────────────────────────────────────────────────────────

/// Build canonical snapshot N.  Matches what `generate_vectors.rs` produces.
fn make_snapshot(index: u8) -> EntropySnapshot {
    let mut bytes = [0u8; 32];
    for (i, b) in bytes.iter_mut().enumerate() {
        *b = index.wrapping_add(i as u8);
    }
    EntropySnapshot {
        bytes,
        timestamp_nanos: 1_000_000_000_000 + (index as u128) * 111_111_111,
    }
}

fn from_hex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn from_hex32(s: &str) -> [u8; 32] {
    let v = from_hex(s);
    let mut arr = [0u8; 32];
    arr.copy_from_slice(&v);
    arr
}

// ─── kk_hash vectors ──────────────────────────────────────────────────────────

#[test]
fn test_vector_kk_hash_empty() {
    let got = kk_hash(b"");
    let want = from_hex32("2081a4b4103da0f32a5bbcb8228bc36a19c631800f932f00f94d85c695a545f6");
    assert_eq!(got, want);
}

#[test]
fn test_vector_kk_hash_one_byte() {
    let got = kk_hash(&[0x42]);
    let want = from_hex32("a69fbef6758d1deb48d7cc9b7243c7ca413180d3ff829bee7ab1b0fa51099c2b");
    assert_eq!(got, want);
}

#[test]
fn test_vector_kk_hash_abc() {
    let got = kk_hash(b"abc");
    let want = from_hex32("781254de54b9026781fa5dd4f9ed02e966a0ef81ae0187727276b93cf19ce849");
    assert_eq!(got, want);
}

#[test]
fn test_vector_kk_hash_32_zeros() {
    let got = kk_hash(&[0u8; 32]);
    let want = from_hex32("94c859282ef2524fd4392df55a42da74413465ea732706cab1f75f96fb9e7eef");
    assert_eq!(got, want);
}

#[test]
fn test_vector_kk_hash_64_ascending() {
    let input: Vec<u8> = (0..64u8).collect();
    let got = kk_hash(&input);
    let want = from_hex32("932f9e8b614bf3d6aef52e65172427ce929d9878c4e6f656cb7435b632550134");
    assert_eq!(got, want);
}

#[test]
fn test_vector_kk_hash_128_xff() {
    let got = kk_hash(&[0xFFu8; 128]);
    let want = from_hex32("d16e0ddae353437d936aa2beade2fc8f6f2b0cf20af3ce62ae5400ab2c6d0c68");
    assert_eq!(got, want);
}

#[test]
fn test_vector_kk_hash_1024_pattern() {
    let input: Vec<u8> = (0..=255u8).cycle().take(1024).collect();
    let got = kk_hash(&input);
    let want = from_hex32("1eadb6b509a40532695dd982aedb150bd72c11a86a836a868ad55d0c915aed37");
    assert_eq!(got, want);
}

#[test]
fn test_vector_kk_hash_64_zeros() {
    let got = kk_hash(&[0u8; 64]);
    let want = from_hex32("2db0b45e77e81c22729a635e87a04e79864ad0f2ff65d40b1c81920149182900");
    assert_eq!(got, want);
}

#[test]
fn test_vector_kk_hash_32_xff() {
    let got = kk_hash(&[0xFFu8; 32]);
    let want = from_hex32("956235eb083a08f2a3c01a38d53256946e22d7f176ee2765b8c63522896daa86");
    assert_eq!(got, want);
}

#[test]
fn test_vector_kk_hash_utf8_hello() {
    let got = kk_hash("Hello, 世界! 🌍".as_bytes());
    let want = from_hex32("6355350e6d2f52830da2e338419fff19269a08b25c323bb2bef5b220c0fb42ed");
    assert_eq!(got, want);
}

// ─── kk_kdf vectors ───────────────────────────────────────────────────────────

#[test]
fn test_vector_kk_kdf_basic_32() {
    let out = kk_kdf(b"secret-key", b"salt-value", b"info-string", 32);
    let want = from_hex("a073324f9f40942784c237d9a55842709a12d8a6a681f20aac88646e07998dc7");
    assert_eq!(out, want);
}

#[test]
fn test_vector_kk_kdf_basic_64() {
    let out = kk_kdf(b"secret-key", b"salt-value", b"info-string", 64);
    let want = from_hex(
        "a073324f9f40942784c237d9a55842709a12d8a6a681f20aac88646e07998dc7\
         bf2496a240f3ca95475e10c605edcbdcf5256bf1b9db5eba824c54c05e4b140e",
    );
    assert_eq!(out, want);
}

#[test]
fn test_vector_kk_kdf_empty_salt() {
    let out = kk_kdf(b"key", b"", b"info", 32);
    let want = from_hex("e595c9a2b5fc2580bf50fa46b36569913afddcc3880a0387e0d1a541a29efb45");
    assert_eq!(out, want);
}

#[test]
fn test_vector_kk_kdf_empty_info() {
    let out = kk_kdf(b"key", b"salt", b"", 32);
    let want = from_hex("18bd800ec382f4d0f3ee5f928288d6c9cae3e34ca35fa873f32bfc8dd30d6e31");
    assert_eq!(out, want);
}

#[test]
fn test_vector_kk_kdf_long_key() {
    let key = vec![0xABu8; 128];
    let out = kk_kdf(&key, b"salt", b"info", 32);
    let want = from_hex("ff4e8a1f64c4775e6ac379851a2247a46e85d1bce8daa21f5c8a75c2bfded7c2");
    assert_eq!(out, want);
}

#[test]
fn test_vector_kk_kdf_long_salt() {
    let salt = vec![0xCDu8; 128];
    let out = kk_kdf(b"key", &salt, b"info", 32);
    let want = from_hex("16593f462261aa86b35557ca3811a72043e11433f52194ea221c73f10845f5b3");
    assert_eq!(out, want);
}

#[test]
fn test_vector_kk_kdf_16_bytes() {
    let out = kk_kdf(b"key", b"salt", b"short", 16);
    let want = from_hex("5292629b4866b5fe500dbae118dd104b");
    assert_eq!(out, want);
}

#[test]
fn test_vector_kk_kdf_128_bytes() {
    let out = kk_kdf(b"key", b"salt", b"long-output", 128);
    let want = from_hex(
        "cd120c10311925e8a28d8d26f1cd610037753c6b7aff47b618d209f6576958b3\
         983c0016bc394b31cd151e2fca332c29bdc7323b85016ace325afd7108bb0b1f\
         ab1c462b6aabe5a4eb30e1d073f9d780e6e8a0a0699fd7c41c2eee8d7289ed5e\
         9e5deed7c72349a9d23ad726e829a8aed9b7d6bcc588d17dee61645c29a17c51",
    );
    assert_eq!(out, want);
}

// ─── kk_mac vectors ───────────────────────────────────────────────────────────

#[test]
fn test_vector_kk_mac_basic() {
    let tag = kk_mac(b"mac-key", b"message-to-authenticate");
    let want = from_hex32("7563661cc20bbb3665dc28ecb6c887ba3d61aa8ca20ab6fd28cc9685d8e7accc");
    assert_eq!(tag, want);
}

#[test]
fn test_vector_kk_mac_empty_msg() {
    let tag = kk_mac(b"mac-key", b"");
    let want = from_hex32("b210c5dedea708cf562473e3f7b48dc7b3a6083a3d5dd2ece1c40f89293614dd");
    assert_eq!(tag, want);
}

#[test]
fn test_vector_kk_mac_long_msg() {
    let msg = vec![0x55u8; 256];
    let tag = kk_mac(b"mac-key", &msg);
    let want = from_hex32("dfb93106ee2a23b50e22b58c1ce831487a15bfbcec7d5c2a4920ba0ec9129d64");
    assert_eq!(tag, want);
}

#[test]
fn test_vector_kk_mac_long_key() {
    let key = vec![0xAAu8; 64];
    let tag = kk_mac(&key, b"short message");
    let want = from_hex32("88d89bc09cb26f480946fab69bcfa0382acd00f78904d54977ed21128f5a8ad1");
    assert_eq!(tag, want);
}

#[test]
fn test_vector_kk_mac_single_byte() {
    let tag = kk_mac(b"k", b"m");
    let want = from_hex32("dc9f3e2e89d8c3024713279d39fc3e784f1b46611ca24344b8792de826d1de04");
    assert_eq!(tag, want);
}

#[test]
fn test_vector_kk_mac_binary() {
    let tag = kk_mac(&[0x00, 0xFF, 0x80], &[0x01, 0x02, 0x03, 0x04]);
    let want = from_hex32("2682565b04d18bdc196680a309cf99a2a422d8cb5173d1fc528de05ffc8aad52");
    assert_eq!(tag, want);
}

// ─── kk_mac_with_entropy vectors ─────────────────────────────────────────────

#[test]
fn test_vector_kk_mac_with_entropy_basic() {
    let snap = make_snapshot(0);
    let tag = kk_mac_with_entropy(b"mac-key", b"message", &snap.bytes);
    let want = from_hex32("3eacbe0c97ac764bb64b4b4029f37e89f88c92f61da9fb17636acccbd35d3977");
    assert_eq!(tag, want);
}

#[test]
fn test_vector_kk_mac_with_entropy_long() {
    let snap = make_snapshot(0);
    let msg = vec![0x55u8; 256];
    let tag = kk_mac_with_entropy(b"mac-key", &msg, &snap.bytes);
    let want = from_hex32("ff8592168320c47c9f82d256d2fa028f0bcc11cc614db76b8cfc44229c7480f2");
    assert_eq!(tag, want);
}

#[test]
fn test_vector_kk_mac_with_entropy_snap1() {
    let snap = make_snapshot(1);
    let tag = kk_mac_with_entropy(b"mac-key", b"message", &snap.bytes);
    let want = from_hex32("472fd5cbf1649455d81d1023cf15961231b645a79b3ccdd9bf42a25c0ee72b67");
    assert_eq!(tag, want);
}

// ─── kk_permute vectors ───────────────────────────────────────────────────────

#[test]
fn test_vector_kk_permute_all_zeros() {
    let mut state: KkState = [0u64; 25];
    kk_permute(&mut state);
    // Expected output as 25 × 8 bytes = 200-byte hex
    let want_hex = "b92e82ee838a507bd21fdd437efc90adf9db823d6506f6043c4c3937d5f1fc82\
         b029a959e50941f76f94bb24f78f3c6028e2dff1b25a73d8afd20706e139e0e1\
         7aab13271513df228b6d37d21e56ebe65adf302c9ceb6ad0bd7e460600eb91a0\
         a5d857a91521c21f6fefbaf4f4315f93daf8a1394652463bcadf505164bad999\
         247dbdb059c16ceab2a0586d76bbcd942e864ed0ed6913379892864d1700f091\
         7516cf78858b01f33e0c2668a8a5813eb84b243e85e9313f3493876943187df7\
         d7d785afbabc0105";
    let want_bytes = from_hex(want_hex);
    let want: KkState = core::array::from_fn(|i| {
        let b = &want_bytes[i * 8..(i + 1) * 8];
        u64::from_be_bytes(b.try_into().unwrap())
    });
    assert_eq!(state, want);
}

#[test]
fn test_vector_kk_permute_ascending() {
    let mut state: KkState = core::array::from_fn(|i| i as u64);
    kk_permute(&mut state);
    let want_hex = "6781c0c9165f451e86b468dbbda9ce929a037c1bcf9d7c7774f1bccd94032027\
         8dd9a138aa72a4998d98e460e9973d46910a93a6bbb5eda75af87d84796c7a24\
         ced27386b19cd8de1f227bea4e2401c8e40379de3702bbba2d33a38789e2a1aa\
         2092c8fa4a93d0a51221068977dba355026affe98aa7cca316be88bac56029b0\
         0fb3d3eb001fdcb85aaff374be45aaa8d03069302000520747fdd9c8d156c77f\
         ebc26ab4a7bba3e061ce047f495e3f90dfbc646995acc83f67bbf5a2ce545eb6\
         f221d0c8bd3d8bcd";
    let want_bytes = from_hex(want_hex);
    let want: KkState = core::array::from_fn(|i| {
        let b = &want_bytes[i * 8..(i + 1) * 8];
        u64::from_be_bytes(b.try_into().unwrap())
    });
    assert_eq!(state, want);
}

#[test]
fn test_vector_kk_permute_custom_rotations_snap0() {
    let rots = rotations_from_entropy(&make_snapshot(0).bytes);
    let mut state: KkState = [0u64; 25];
    kk_permute_with_schedule(&mut state, &rots);
    let want_hex = "2767ad8f3dcf4c42baf4d126d3ef826ac6135af36ae6b9a1b77ba42f018dcd5a\
         d0018d8fa16f9dcc718bff87356137192488e355d36fe68f2dd8d66f071b6a47\
         4b58e6a28b62f3c8e1d2d0b6ea0ed0ec3b2fe17b2ece8549f8ba7b68ffab6310\
         ea228885bfd8939882ae132b78b27eee1641dc6d6b37f7306582f8b25980aa28\
         46b294c4ab2d5779b420a581c0cdce52ebaae0fb7c3e40901be5642070af3b90\
         68ce40fe489aa4fce4a6be1b7457f57e204a0de91548e088fd80b7c376f982c2\
         594afba6fd82851e";
    let want_bytes = from_hex(want_hex);
    let want: KkState = core::array::from_fn(|i| {
        let b = &want_bytes[i * 8..(i + 1) * 8];
        u64::from_be_bytes(b.try_into().unwrap())
    });
    assert_eq!(state, want);
}

#[test]
fn test_vector_kk_permute_custom_rotations_snap2() {
    let rots = rotations_from_entropy(&make_snapshot(2).bytes);
    let mut state: KkState = [0u64; 25];
    kk_permute_with_schedule(&mut state, &rots);
    let want_hex = "460a09bc4f80931653b1a07259da977040589cb505c3b0b0e439d0389d1ad72b\
         5af954f07086a7bc0c0ddc0de127be31fe5412a5c1815e9fe675e9774ef2ea49\
         2d21e47672e607d88e361f3a7f8e78fd8f1128df6fc59a874b64aea15441daa7\
         da153c3ab2f1def1a56ea5a66eb0d8edc0709b368cfbcc45747d22fba448e95c\
         3c1573ac95138552f7863b3b4d81642c2ddfb3a387ad4e1a809da1e3c0dcf92e\
         7daf2b4dd8632c41db6450a68328d0a477dd57dc152ed3a25d2fd79438aee345\
         e552b52a631dff47";
    let want_bytes = from_hex(want_hex);
    let want: KkState = core::array::from_fn(|i| {
        let b = &want_bytes[i * 8..(i + 1) * 8];
        u64::from_be_bytes(b.try_into().unwrap())
    });
    assert_eq!(state, want);
}

// ─── rotations_from_entropy vectors ──────────────────────────────────────────

#[test]
fn test_vector_rotations_from_entropy_snap0() {
    let rots = rotations_from_entropy(&make_snapshot(0).bytes);
    let want: [[u32; 2]; 15] = [
        [1, 1],
        [3, 3],
        [5, 5],
        [7, 7],
        [9, 9],
        [11, 11],
        [13, 13],
        [15, 15],
        [17, 17],
        [19, 19],
        [21, 21],
        [23, 23],
        [25, 25],
        [27, 27],
        [29, 29],
    ];
    assert_eq!(rots, want);
}

#[test]
fn test_vector_rotations_from_entropy_snap1() {
    let rots = rotations_from_entropy(&make_snapshot(1).bytes);
    let want: [[u32; 2]; 15] = [
        [1, 3],
        [3, 5],
        [5, 7],
        [7, 9],
        [9, 11],
        [11, 13],
        [13, 15],
        [15, 17],
        [17, 19],
        [19, 21],
        [21, 23],
        [23, 25],
        [25, 27],
        [27, 29],
        [29, 31],
    ];
    assert_eq!(rots, want);
}

#[test]
fn test_vector_rotations_from_entropy_snap2() {
    let rots = rotations_from_entropy(&make_snapshot(2).bytes);
    let want: [[u32; 2]; 15] = [
        [3, 3],
        [5, 5],
        [7, 7],
        [9, 9],
        [11, 11],
        [13, 13],
        [15, 15],
        [17, 17],
        [19, 19],
        [21, 21],
        [23, 23],
        [25, 25],
        [27, 27],
        [29, 29],
        [31, 31],
    ];
    assert_eq!(rots, want);
}

// ─── encode/decode with fixed snapshot ───────────────────────────────────────

#[test]
fn test_vector_encode_hello() {
    let snap = make_snapshot(0);
    let packet = encode_with_snapshot(b"shared-secret", b"Hello, KK!", snap).unwrap();
    let want_ct = from_hex("c5b0ed5c8133a6faf2a5");
    let want_mac = from_hex32("da71d91f9f597380637c062e70e51ca92f8846f32c24adc92a7c27918d373c19");
    assert_eq!(packet.ciphertext, want_ct);
    assert_eq!(packet.commitment.mac, want_mac);
    let recovered = decode(b"shared-secret", &packet).unwrap();
    assert_eq!(recovered, b"Hello, KK!");
}

#[test]
fn test_vector_encode_binary() {
    let snap = make_snapshot(1);
    let packet = encode_with_snapshot(b"key-two", &[0x00, 0xFF, 0x80, 0x7F], snap).unwrap();
    let want_ct = from_hex("b59b8aa0");
    let want_mac = from_hex32("6102cceee9305e39587b6946d18b85ddc61b9207fc1f9d310c7d712c8d24b891");
    assert_eq!(packet.ciphertext, want_ct);
    assert_eq!(packet.commitment.mac, want_mac);
    let recovered = decode(b"key-two", &packet).unwrap();
    assert_eq!(recovered, [0x00, 0xFF, 0x80, 0x7F]);
}

#[test]
fn test_vector_encode_long() {
    let snap = make_snapshot(2);
    let plaintext = b"The quick brown fox jumps over the lazy dog";
    let packet = encode_with_snapshot(b"key-three", plaintext, snap).unwrap();
    let want_ct = from_hex(
        "b4e89c42bcc35ce1cf1691c56ce91d25df806b35552d5a6b9a0b3cc97b404a82784589c80edcfc8cd1aef8",
    );
    let want_mac = from_hex32("4943ca880883c5afbe9e01b6d60eedfcd4f42785143b3278f00a5e87e9c8d37a");
    assert_eq!(packet.ciphertext, want_ct);
    assert_eq!(packet.commitment.mac, want_mac);
    let recovered = decode(b"key-three", &packet).unwrap();
    assert_eq!(recovered, plaintext);
}

#[test]
fn test_vector_encode_single_byte() {
    let snap = make_snapshot(3);
    let packet = encode_with_snapshot(b"k", b"X", snap).unwrap();
    let want_ct = from_hex("57");
    let want_mac = from_hex32("9cb0206ec34dc9b3718efd044118f8cf59c3e169b80cda6e01fa7507c05bc0b9");
    assert_eq!(packet.ciphertext, want_ct);
    assert_eq!(packet.commitment.mac, want_mac);
    let recovered = decode(b"k", &packet).unwrap();
    assert_eq!(recovered, b"X");
}

// ─── encode_aead with fixed snapshot ─────────────────────────────────────────

#[test]
fn test_vector_encode_aead_basic() {
    let snap = make_snapshot(0);
    let packet =
        encode_aead_with_snapshot(b"shared-secret", b"Hello AEAD!", b"header-v1", snap).unwrap();
    let want_ct = from_hex("c5b0ed5c813fc7f4f8c077");
    let want_mac = from_hex32("7893aaa3cd9d560a37e862902c25e8e2f804c4b0e8c86211ddf3c7b324a92786");
    assert_eq!(packet.ciphertext, want_ct);
    assert_eq!(packet.commitment.mac, want_mac);
    let recovered = decode_aead(b"shared-secret", &packet).unwrap();
    assert_eq!(recovered, b"Hello AEAD!");
}

#[test]
fn test_vector_encode_aead_empty_aad() {
    let snap = make_snapshot(1);
    let packet = encode_aead_with_snapshot(b"key-two", b"payload", b"", snap).unwrap();
    let want_ct = from_hex("c50573b33ee9ab");
    let want_mac = from_hex32("6f3e114e75351f2458bdc000c07f410ab2ac4a0c0a8bdb4e8d68a93140520ad8");
    assert_eq!(packet.ciphertext, want_ct);
    assert_eq!(packet.commitment.mac, want_mac);
    let recovered = decode_aead(b"key-two", &packet).unwrap();
    assert_eq!(recovered, b"payload");
}

#[test]
fn test_vector_encode_aead_long_aad() {
    let snap = make_snapshot(2);
    let aad = vec![0xAAu8; 64];
    let packet = encode_aead_with_snapshot(b"key-three", b"msg", &aad, snap).unwrap();
    let want_ct = from_hex("8df39e");
    let want_mac = from_hex32("aa1a7341723f1258f8a7c1e711541654c101f55118a1e71822f1ea722c280821");
    assert_eq!(packet.ciphertext, want_ct);
    assert_eq!(packet.commitment.mac, want_mac);
    let recovered = decode_aead(b"key-three", &packet).unwrap();
    assert_eq!(recovered, b"msg");
}

// ─── RopeRatchet deterministic advance ───────────────────────────────────────

#[test]
fn test_vector_rope_ratchet_sequential_steps() {
    let mut ratchet = RopeRatchet::new(b"session-secret", b"alice-to-bob").unwrap();

    let want_keys = [
        from_hex32("46529734b3e5b0c63e6ebfdb9aef4d5cb32635efe198f5ebab862c50c496bcc2"),
        from_hex32("679104ec780d54fba831507a7b26013e5bd248da56f216b051a7bf0a35df04d7"),
        from_hex32("57310684fed2eaa5665cfc680db0753936999e2d2f3cfff47d72bfeca2eabc3a"),
    ];

    for (i, want_key) in want_keys.iter().enumerate() {
        let snap = make_snapshot(i as u8);
        let (key, step) = ratchet.advance_with_snapshot(snap).unwrap();
        assert_eq!(&key, want_key, "ratchet step {} key mismatch", i);
        assert_eq!(
            step.counter,
            (i + 1) as u64,
            "ratchet step {} counter mismatch",
            i
        );
    }
}

#[test]
fn test_vector_rope_ratchet_step0_key() {
    let mut ratchet = RopeRatchet::new(b"session-secret", b"alice-to-bob").unwrap();
    let snap = make_snapshot(0);
    let (key, step) = ratchet.advance_with_snapshot(snap).unwrap();
    let want = from_hex32("46529734b3e5b0c63e6ebfdb9aef4d5cb32635efe198f5ebab862c50c496bcc2");
    assert_eq!(key, want);
    assert_eq!(step.counter, 1);
}

#[test]
fn test_vector_rope_ratchet_step2_key() {
    // Advance twice, confirm step-2 key is independent of what we do with step 0/1
    let mut ratchet = RopeRatchet::new(b"session-secret", b"alice-to-bob").unwrap();
    let _ = ratchet.advance_with_snapshot(make_snapshot(0)).unwrap();
    let _ = ratchet.advance_with_snapshot(make_snapshot(1)).unwrap();
    let (key, step) = ratchet.advance_with_snapshot(make_snapshot(2)).unwrap();
    let want = from_hex32("57310684fed2eaa5665cfc680db0753936999e2d2f3cfff47d72bfeca2eabc3a");
    assert_eq!(key, want);
    assert_eq!(step.counter, 3);
}
