// Copyright (c) 2026 John A Keeney, Entrouter. All rights reserved.
// Licensed under the Apache License, Version 2.0 with Additional Terms.
// NO COMMERCIAL USE without prior written authorization from Entrouter.
// Unauthorized commercial use will be prosecuted to the fullest extent of the law.
// See the LICENSE file in the project root for full license information.
// NOTICE: Removal of this header is a violation of the license.

//! Deterministic test vectors for all KK cryptographic primitives.
//!
//! Every value in this file was generated by `examples/generate_vectors.rs`
//! and is considered a canonical reference.  Any change to the underlying
//! primitives that causes a test here to fail is a **breaking change** and
//! must be explicitly acknowledged before updating the vectors.
//!
//! To regenerate vectors after an intentional change:
//!   `cargo run --example generate_vectors`
//! Then manually update the constants below and `KK_TEST_VECTORS.md`.

use kk_crypto::entropy::EntropySnapshot;
use kk_crypto::kk_mix::{
    kk_hash, kk_kdf, kk_mac, kk_mac_with_entropy, kk_permute,
    kk_permute_with_schedule, rotations_from_entropy, KkState,
};
use kk_crypto::{decode, decode_aead, encode_aead_with_snapshot, encode_with_snapshot};
use kk_crypto::session::RopeRatchet;

// ─── helpers ─────────────────────────────────────────────────────────────────

/// Build canonical snapshot N.  Matches what `generate_vectors.rs` produces.
fn make_snapshot(index: u8) -> EntropySnapshot {
    let mut bytes = [0u8; 32];
    for (i, b) in bytes.iter_mut().enumerate() {
        *b = index.wrapping_add(i as u8);
    }
    EntropySnapshot {
        bytes,
        timestamp_nanos: 1_000_000_000_000 + (index as u128) * 111_111_111,
    }
}

fn from_hex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn from_hex32(s: &str) -> [u8; 32] {
    let v = from_hex(s);
    let mut arr = [0u8; 32];
    arr.copy_from_slice(&v);
    arr
}

// ─── kk_hash vectors ──────────────────────────────────────────────────────────

#[test]
fn test_vector_kk_hash_empty() {
    let got = kk_hash(b"");
    let want = from_hex32("04a533c98a06efc6ce3ce4273c99b676c55c50f3161594449ef19247a252bbc0");
    assert_eq!(got, want);
}

#[test]
fn test_vector_kk_hash_one_byte() {
    let got = kk_hash(&[0x42]);
    let want = from_hex32("da19e1beb58c23aab39dcafef9bad389364d3d11bc0629379ac85e7121ec099a");
    assert_eq!(got, want);
}

#[test]
fn test_vector_kk_hash_abc() {
    let got = kk_hash(b"abc");
    let want = from_hex32("01cb6567315b935c09b5f1a67bbb11e7a81af313a48673771d8df473dac293d1");
    assert_eq!(got, want);
}

#[test]
fn test_vector_kk_hash_32_zeros() {
    let got = kk_hash(&[0u8; 32]);
    let want = from_hex32("37ba255285179e3a6f6d8bff60f6633ac7a4430da0a4ae7223fe9de4a2de906b");
    assert_eq!(got, want);
}

#[test]
fn test_vector_kk_hash_64_ascending() {
    let input: Vec<u8> = (0..64u8).collect();
    let got = kk_hash(&input);
    let want = from_hex32("ede4342b33d7f61e7923ce2b013931d89dcbd6429756e2cae31ed30f0bdc8d27");
    assert_eq!(got, want);
}

#[test]
fn test_vector_kk_hash_128_xff() {
    let got = kk_hash(&[0xFFu8; 128]);
    let want = from_hex32("507ec1af5b83509863eb5207b5b839d64a98462f0d39443217bb0cc231a7df83");
    assert_eq!(got, want);
}

#[test]
fn test_vector_kk_hash_1024_pattern() {
    let input: Vec<u8> = (0..=255u8).cycle().take(1024).collect();
    let got = kk_hash(&input);
    let want = from_hex32("ce76c6f1d136af7761cfb53d1b7bc4d18d86125bfa7bad1445c00e03abafaee3");
    assert_eq!(got, want);
}

#[test]
fn test_vector_kk_hash_64_zeros() {
    let got = kk_hash(&[0u8; 64]);
    let want = from_hex32("b83788779871169dcbc5fb20da0b6c8d48b54d39c05a8c8f4b6d2b5828e07166");
    assert_eq!(got, want);
}

#[test]
fn test_vector_kk_hash_32_xff() {
    let got = kk_hash(&[0xFFu8; 32]);
    let want = from_hex32("ad67b1ddc16965ecfb8cbc63a1c38a9b6d7b35d0100cbe2e522d686b3a8c0f3a");
    assert_eq!(got, want);
}

#[test]
fn test_vector_kk_hash_utf8_hello() {
    let got = kk_hash("Hello, 世界! 🌍".as_bytes());
    let want = from_hex32("13369518d7cabb030ddb210ed5ff593209dd105caa4e9cd8ddde57e7dccb7f6c");
    assert_eq!(got, want);
}

// ─── kk_kdf vectors ───────────────────────────────────────────────────────────

#[test]
fn test_vector_kk_kdf_basic_32() {
    let out = kk_kdf(b"secret-key", b"salt-value", b"info-string", 32);
    let want = from_hex("e38cb42abc73a49122f792dd4b243e56b7eede78a24275c20738f02792edcc94");
    assert_eq!(out, want);
}

#[test]
fn test_vector_kk_kdf_basic_64() {
    let out = kk_kdf(b"secret-key", b"salt-value", b"info-string", 64);
    let want = from_hex(
        "e38cb42abc73a49122f792dd4b243e56b7eede78a24275c20738f02792edcc94\
         1cb06e3219199539e179db66bdab68c5748bf0c5a3bfa940e760000bdd6b6ab1",
    );
    assert_eq!(out, want);
}

#[test]
fn test_vector_kk_kdf_empty_salt() {
    let out = kk_kdf(b"key", b"", b"info", 32);
    let want = from_hex("d8ee9f9b5af750639711fb1309d57fe79d91c64cc1f89f2e97c7a760c9a64371");
    assert_eq!(out, want);
}

#[test]
fn test_vector_kk_kdf_empty_info() {
    let out = kk_kdf(b"key", b"salt", b"", 32);
    let want = from_hex("8bb41b65caa5d0ccceb8ea5905b08b73e001ac2ce79a117da69e83998dab97d1");
    assert_eq!(out, want);
}

#[test]
fn test_vector_kk_kdf_long_key() {
    let key = vec![0xABu8; 128];
    let out = kk_kdf(&key, b"salt", b"info", 32);
    let want = from_hex("d05b9a4ee71ca5f3ef8f86b998bcb8201dd6e43f2ce7f661c2e213fccef942b5");
    assert_eq!(out, want);
}

#[test]
fn test_vector_kk_kdf_long_salt() {
    let salt = vec![0xCDu8; 128];
    let out = kk_kdf(b"key", &salt, b"info", 32);
    let want = from_hex("299fa3bf11e2fef52de1c75a51423cffbeea5ea71ebc11ffaadaff42137e6a9e");
    assert_eq!(out, want);
}

#[test]
fn test_vector_kk_kdf_16_bytes() {
    let out = kk_kdf(b"key", b"salt", b"short", 16);
    let want = from_hex("9db5ac7d34ff30a8f2fc58bc3b440ada");
    assert_eq!(out, want);
}

#[test]
fn test_vector_kk_kdf_128_bytes() {
    let out = kk_kdf(b"key", b"salt", b"long-output", 128);
    let want = from_hex(
        "2fb81c9b7514a28ab4b05bfbc71fdf3e7f21a75cc91962459d459524a3276815\
         aa2f68dac23cfc1670e36b37cf42445bcd5e6e1aea05bf680c9ab86410e0ca1f\
         c50695f14a177fbf89f4c4ffd724309ba26672f14d97a2f3c64eac4f266e388f\
         5e8431b6b345eb72f2ee3643ebea406f3ecc5d4623ac517baba2a6551df8db25",
    );
    assert_eq!(out, want);
}

// ─── kk_mac vectors ───────────────────────────────────────────────────────────

#[test]
fn test_vector_kk_mac_basic() {
    let tag = kk_mac(b"mac-key", b"message-to-authenticate");
    let want = from_hex32("e73f40f74a03f180aace3bccfddf086df5fb89efbcdab368454f04bb1975a779");
    assert_eq!(tag, want);
}

#[test]
fn test_vector_kk_mac_empty_msg() {
    let tag = kk_mac(b"mac-key", b"");
    let want = from_hex32("df2f287497c167010c682795143d935e1c70e057799300b710dfafa250a86b81");
    assert_eq!(tag, want);
}

#[test]
fn test_vector_kk_mac_long_msg() {
    let msg = vec![0x55u8; 256];
    let tag = kk_mac(b"mac-key", &msg);
    let want = from_hex32("36219aa06c61f96c5926d8bba94be5833a21fc7d2dda5c56de7553b388f78cfb");
    assert_eq!(tag, want);
}

#[test]
fn test_vector_kk_mac_long_key() {
    let key = vec![0xAAu8; 64];
    let tag = kk_mac(&key, b"short message");
    let want = from_hex32("c7c0b167160ae524b2d2f13d254d805b1957c8d7d43b2ec5cc3c6d59ea5a3879");
    assert_eq!(tag, want);
}

#[test]
fn test_vector_kk_mac_single_byte() {
    let tag = kk_mac(b"k", b"m");
    let want = from_hex32("9345e56e858c171f4ea6e683bc36e5985bbb480889711dedba92eb0ba476423e");
    assert_eq!(tag, want);
}

#[test]
fn test_vector_kk_mac_binary() {
    let tag = kk_mac(&[0x00, 0xFF, 0x80], &[0x01, 0x02, 0x03, 0x04]);
    let want = from_hex32("41b038c43ed76b9a92d3b6f8e3c2280794c1199ce2602c4c62993e6b33bf7eb1");
    assert_eq!(tag, want);
}

// ─── kk_mac_with_entropy vectors ─────────────────────────────────────────────

#[test]
fn test_vector_kk_mac_with_entropy_basic() {
    let snap = make_snapshot(0);
    let tag = kk_mac_with_entropy(b"mac-key", b"message", &snap.bytes);
    let want = from_hex32("bf7cfd10fb92b6a3ba09bb51ea41d59b4a6d3c38bb156f7a3f02a5993d18ac24");
    assert_eq!(tag, want);
}

#[test]
fn test_vector_kk_mac_with_entropy_long() {
    let snap = make_snapshot(0);
    let msg = vec![0x55u8; 256];
    let tag = kk_mac_with_entropy(b"mac-key", &msg, &snap.bytes);
    let want = from_hex32("8152ff3a06e28a204dc61d19eb4d501c82c2e18aed3387b5968eef49c198f589");
    assert_eq!(tag, want);
}

#[test]
fn test_vector_kk_mac_with_entropy_snap1() {
    let snap = make_snapshot(1);
    let tag = kk_mac_with_entropy(b"mac-key", b"message", &snap.bytes);
    let want = from_hex32("f4d793a91818ded823f05616c9e01821fac3dc04efd5b4c88f448d90b077a7b8");
    assert_eq!(tag, want);
}

// ─── kk_permute vectors ───────────────────────────────────────────────────────

#[test]
fn test_vector_kk_permute_all_zeros() {
    let mut state: KkState = [0u64; 25];
    kk_permute(&mut state);
    // Expected output as 25 × 8 bytes = 200-byte hex
    let want_hex =
        "e582af7a2d6fe6bb8e2af9c30cbd668d5e5d357ada6d1a1e7e5de5640cfa0fc1\
         fff6c6e933a7be99c82ffb3c999ad72e214c205fe29ed271728c5972c9bf91ec\
         28cae91ebe18c484a78ed9439235397ad98e46ce5b371cf26afe7a71661932ce\
         0145d6f370056da3d467906207ddd169512add34d2d797b8f67646a9d34a1c2e\
         00000000000000003992133aa53fb34f00000000000000000000000000000000\
         1165aa51b525350eeeace4e3a4b76fec4b32c1ee3c2bb2df0000000000000000\
         caf151e5e4d938b3";
    let want_bytes = from_hex(want_hex);
    let want: KkState = core::array::from_fn(|i| {
        let b = &want_bytes[i * 8..(i + 1) * 8];
        u64::from_be_bytes(b.try_into().unwrap())
    });
    assert_eq!(state, want);
}

#[test]
fn test_vector_kk_permute_ascending() {
    let mut state: KkState = core::array::from_fn(|i| i as u64);
    kk_permute(&mut state);
    let want_hex =
        "05121470107bc01cb74ca6140bc9c92cde01c354fa1ae47498e8791ddab9e066\
         9d962762c182cf1b3bb210feefef9e5fc4529b0478b58ec06eff2c687fdd7dcb\
         4010c3f3e0011e8bdd9dd53d97b330fa18205b89737c8f07f1a6c808910525e6\
         a312925c5782db38299c81886d816a4fc25ba9011c5c1bb81f98a729d93a0b14\
         bf63d8422cdfccbef8e918a863b28354a5076a9472560c59bbf600e6228d0bf9\
         7189c413efd374d26ba04d7b18c766e450973d6cfcbfc35e961e2a134c7fba64\
         63ca9198aa423aa3";
    let want_bytes = from_hex(want_hex);
    let want: KkState = core::array::from_fn(|i| {
        let b = &want_bytes[i * 8..(i + 1) * 8];
        u64::from_be_bytes(b.try_into().unwrap())
    });
    assert_eq!(state, want);
}

#[test]
fn test_vector_kk_permute_custom_rotations_snap0() {
    let rots = rotations_from_entropy(&make_snapshot(0).bytes);
    let mut state: KkState = [0u64; 25];
    kk_permute_with_schedule(&mut state, &rots);
    let want_hex =
        "773aec528fe93fbbd2aa91aafc05ae031c9f986f5fd634930b352aadcf6892aa\
         9b3120a33ef25d3d919dbd1d6cc3c0a696291846cc9860bb2778cdcccab1da6d\
         5e733b5c622a2e66b83027b59920bfef2af61c1a0de7f857705eb4e0c513e9f4\
         e68751dccead1edb3fcf48a96b5f909d36657f0aad37dfa402c2f0c2d2e4ca68\
         00000000000000007bc448c602c8d628000000000000000000000000000000004\
         3df812e4a935e7328c6a1f11672f85b7d424032fd7264c200000000000000003\
         cc4a374f0ba2637";
    let want_bytes = from_hex(want_hex);
    let want: KkState = core::array::from_fn(|i| {
        let b = &want_bytes[i * 8..(i + 1) * 8];
        u64::from_be_bytes(b.try_into().unwrap())
    });
    assert_eq!(state, want);
}

#[test]
fn test_vector_kk_permute_custom_rotations_snap2() {
    let rots = rotations_from_entropy(&make_snapshot(2).bytes);
    let mut state: KkState = [0u64; 25];
    kk_permute_with_schedule(&mut state, &rots);
    let want_hex =
        "03e7630b17d18e841b2a2f8d5430f2a1e54a5c375f66ad0dcb7d8f36f38142d2\
         48b6866df717e1c61b4e2de41ee32ca944079866e1be230fc8f19e20e4507ef9\
         242381e52e4e4497a77f94fc3961d03c555a7a4ad197234ff51bcb6b3499d86f\
         0ac4b0c20a565c15e5aeb7383993d27bfcbc6c7018037dd291160e79f8fea926\
         00000000000000004bc911201ed72fc5000000000000000000000000000000006\
         47f400a1486b42376979cf8ca184c9dd376361a8aa3721b00000000000000007\
         e6442bd5f7ba6a4";
    let want_bytes = from_hex(want_hex);
    let want: KkState = core::array::from_fn(|i| {
        let b = &want_bytes[i * 8..(i + 1) * 8];
        u64::from_be_bytes(b.try_into().unwrap())
    });
    assert_eq!(state, want);
}

// ─── rotations_from_entropy vectors ──────────────────────────────────────────

#[test]
fn test_vector_rotations_from_entropy_snap0() {
    let rots = rotations_from_entropy(&make_snapshot(0).bytes);
    let want: [[u32; 2]; 15] = [
        [1, 1], [3, 3], [5, 5], [7, 7], [9, 9], [11, 11], [13, 13], [15, 15],
        [17, 17], [19, 19], [21, 21], [23, 23], [25, 25], [27, 27], [29, 29],
    ];
    assert_eq!(rots, want);
}

#[test]
fn test_vector_rotations_from_entropy_snap1() {
    let rots = rotations_from_entropy(&make_snapshot(1).bytes);
    let want: [[u32; 2]; 15] = [
        [1, 3], [3, 5], [5, 7], [7, 9], [9, 11], [11, 13], [13, 15], [15, 17],
        [17, 19], [19, 21], [21, 23], [23, 25], [25, 27], [27, 29], [29, 31],
    ];
    assert_eq!(rots, want);
}

#[test]
fn test_vector_rotations_from_entropy_snap2() {
    let rots = rotations_from_entropy(&make_snapshot(2).bytes);
    let want: [[u32; 2]; 15] = [
        [3, 3], [5, 5], [7, 7], [9, 9], [11, 11], [13, 13], [15, 15], [17, 17],
        [19, 19], [21, 21], [23, 23], [25, 25], [27, 27], [29, 29], [31, 31],
    ];
    assert_eq!(rots, want);
}

// ─── encode/decode with fixed snapshot ───────────────────────────────────────

#[test]
fn test_vector_encode_hello() {
    let snap = make_snapshot(0);
    let packet = encode_with_snapshot(b"shared-secret", b"Hello, KK!", snap).unwrap();
    let want_ct = from_hex("bb27129666cc32a682ec");
    let want_mac = from_hex32("8f5f2c5010a31fd253ef659c5e4009bdcc88501fda539c5ab0c6a6658072f39b");
    assert_eq!(packet.ciphertext, want_ct);
    assert_eq!(packet.commitment.mac, want_mac);
    let recovered = decode(b"shared-secret", &packet).unwrap();
    assert_eq!(recovered, b"Hello, KK!");
}

#[test]
fn test_vector_encode_binary() {
    let snap = make_snapshot(1);
    let packet = encode_with_snapshot(b"key-two", &[0x00, 0xFF, 0x80, 0x7F], snap).unwrap();
    let want_ct = from_hex("e153fd55");
    let want_mac = from_hex32("4e09bde27661e7c754275a6617bae799422c9117cf24a816f4011d4a71c2c6d5");
    assert_eq!(packet.ciphertext, want_ct);
    assert_eq!(packet.commitment.mac, want_mac);
    let recovered = decode(b"key-two", &packet).unwrap();
    assert_eq!(recovered, [0x00, 0xFF, 0x80, 0x7F]);
}

#[test]
fn test_vector_encode_long() {
    let snap = make_snapshot(2);
    let plaintext = b"The quick brown fox jumps over the lazy dog";
    let packet = encode_with_snapshot(b"key-three", plaintext, snap).unwrap();
    let want_ct = from_hex("08f3c2a10e74a1fa59b66557f603bb370dc56075f45f57cc88f150fef67b2662153c63daa95372cdd07906");
    let want_mac = from_hex32("e197fc2127d74fdccd56843bf3049409d6d5d8dec1c8f41eded3389c6bce38ff");
    assert_eq!(packet.ciphertext, want_ct);
    assert_eq!(packet.commitment.mac, want_mac);
    let recovered = decode(b"key-three", &packet).unwrap();
    assert_eq!(recovered, plaintext);
}

#[test]
fn test_vector_encode_single_byte() {
    let snap = make_snapshot(3);
    let packet = encode_with_snapshot(b"k", b"X", snap).unwrap();
    let want_ct = from_hex("60");
    let want_mac = from_hex32("1d4976e00e5c5dca7437a270e538080d1815a96f528d417970eb710e5a94352a");
    assert_eq!(packet.ciphertext, want_ct);
    assert_eq!(packet.commitment.mac, want_mac);
    let recovered = decode(b"k", &packet).unwrap();
    assert_eq!(recovered, b"X");
}

// ─── encode_aead with fixed snapshot ─────────────────────────────────────────

#[test]
fn test_vector_encode_aead_basic() {
    let snap = make_snapshot(0);
    let packet = encode_aead_with_snapshot(b"shared-secret", b"Hello AEAD!", b"header-v1", snap).unwrap();
    let want_ct = from_hex("bb27129666c053a8888928");
    let want_mac = from_hex32("be90d081d0792edf1ce6b684806628324c6debc8a552098d0871b7960072d59c");
    assert_eq!(packet.ciphertext, want_ct);
    assert_eq!(packet.commitment.mac, want_mac);
    let recovered = decode_aead(b"shared-secret", &packet).unwrap();
    assert_eq!(recovered, b"Hello AEAD!");
}

#[test]
fn test_vector_encode_aead_empty_aad() {
    let snap = make_snapshot(1);
    let packet = encode_aead_with_snapshot(b"key-two", b"payload", b"", snap).unwrap();
    let want_ct = from_hex("91cd044613df0e");
    let want_mac = from_hex32("7494b84b0a9d5e3c4dc3d4b3a833fe30d1cb903ef3c6e68d1f0d977b7a9d74c7");
    assert_eq!(packet.ciphertext, want_ct);
    assert_eq!(packet.commitment.mac, want_mac);
    let recovered = decode_aead(b"key-two", &packet).unwrap();
    assert_eq!(recovered, b"payload");
}

#[test]
fn test_vector_encode_aead_long_aad() {
    let snap = make_snapshot(2);
    let aad = vec![0xAAu8; 64];
    let packet = encode_aead_with_snapshot(b"key-three", b"msg", &aad, snap).unwrap();
    let want_ct = from_hex("31e8c0");
    let want_mac = from_hex32("697023636a5a268ea100e27985ff5cc25999e0e10d31fda7430de332bce77e04");
    assert_eq!(packet.ciphertext, want_ct);
    assert_eq!(packet.commitment.mac, want_mac);
    let recovered = decode_aead(b"key-three", &packet).unwrap();
    assert_eq!(recovered, b"msg");
}

// ─── RopeRatchet deterministic advance ───────────────────────────────────────

#[test]
fn test_vector_rope_ratchet_sequential_steps() {
    let mut ratchet = RopeRatchet::new(b"session-secret", b"alice-to-bob").unwrap();

    let want_keys = [
        from_hex32("9aecc651565bc8b5451d24344d2872de3b1b90cddbcb9298d124dbdd38935219"),
        from_hex32("6c1449a4f1961bd105c37288ef40cabd75021b53ab4e29c753f17528fc5aaad6"),
        from_hex32("65c91bc85c35ba075a85b4025a7d38ed1d6c312fb2d0bc5f75b4343d60d67257"),
    ];

    for (i, want_key) in want_keys.iter().enumerate() {
        let snap = make_snapshot(i as u8);
        let (key, step) = ratchet.advance_with_snapshot(snap).unwrap();
        assert_eq!(&key, want_key, "ratchet step {} key mismatch", i);
        assert_eq!(step.counter, (i + 1) as u64, "ratchet step {} counter mismatch", i);
    }
}

#[test]
fn test_vector_rope_ratchet_step0_key() {
    let mut ratchet = RopeRatchet::new(b"session-secret", b"alice-to-bob").unwrap();
    let snap = make_snapshot(0);
    let (key, step) = ratchet.advance_with_snapshot(snap).unwrap();
    let want = from_hex32("9aecc651565bc8b5451d24344d2872de3b1b90cddbcb9298d124dbdd38935219");
    assert_eq!(key, want);
    assert_eq!(step.counter, 1);
}

#[test]
fn test_vector_rope_ratchet_step2_key() {
    // Advance twice, confirm step-2 key is independent of what we do with step 0/1
    let mut ratchet = RopeRatchet::new(b"session-secret", b"alice-to-bob").unwrap();
    let _ = ratchet.advance_with_snapshot(make_snapshot(0)).unwrap();
    let _ = ratchet.advance_with_snapshot(make_snapshot(1)).unwrap();
    let (key, step) = ratchet.advance_with_snapshot(make_snapshot(2)).unwrap();
    let want = from_hex32("65c91bc85c35ba075a85b4025a7d38ed1d6c312fb2d0bc5f75b4343d60d67257");
    assert_eq!(key, want);
    assert_eq!(step.counter, 3);
}
