# Copyright (c) 2026 John A Keeney, Entrouter. All rights reserved.
# Licensed under the Apache License, Version 2.0 with Additional Terms.
# NO COMMERCIAL USE without prior written authorization from Entrouter.
# Unauthorized commercial use will be prosecuted to the fullest extent of the law.
# See the LICENSE file in the project root for full license information.
# NOTICE: Removal of this header is a violation of the license.

[package]
name = "kk-crypto-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.kk-crypto]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "hash_fuzz"
path = "fuzz_targets/hash_fuzz.rs"
doc = false

[[bin]]
name = "kdf_fuzz"
path = "fuzz_targets/kdf_fuzz.rs"
doc = false

[[bin]]
name = "mac_fuzz"
path = "fuzz_targets/mac_fuzz.rs"
doc = false

[[bin]]
name = "roundtrip_fuzz"
path = "fuzz_targets/roundtrip_fuzz.rs"
doc = false
